[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "python agmarknet_scraper.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
FLASK_ENV = "production"
CHROME_HEADLESS = "true"
CHROME_NO_SANDBOX = "true"
PORT = "5000"
PYTHONUNBUFFERED = "1"
DISPLAY = ":99"